version: '3.7'
services:
  debian:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/myapp

  alpine:
    build:
      context: docker
      dockerfile: Dockerfile.alpine
    volumes:
      - ./:/usr/src/myapp